/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package file_locker.pkg3_level_sequrity;

import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class Addauser extends javax.swing.JFrame {

    /**
     * Creates new form Addauser
     */
    public Addauser() {
        initComponents();
        setBounds(new java.awt.Rectangle(1, 1, 750, 450));
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nn = new javax.swing.JTextField();
        pin2 = new javax.swing.JTextField();
        phoneno3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(190, 100, 140, 40);

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Phone No");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(190, 220, 140, 40);

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password/PIN ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(190, 160, 140, 40);

        nn.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        getContentPane().add(nn);
        nn.setBounds(330, 100, 230, 40);
        getContentPane().add(pin2);
        pin2.setBounds(330, 160, 230, 40);
        getContentPane().add(phoneno3);
        phoneno3.setBounds(330, 220, 230, 40);

        jButton1.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/file_locker/pkg3_level_sequrity/images/protection (1).png"))); // NOI18N
        jButton1.setText("Save And Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(410, 310, 310, 70);

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 3, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Register New User");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 20, 710, 50);

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 3, 36)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Desktop\\Capture.JPG")); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 770, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (nn.getText().length() < 1) {
            JOptionPane.showMessageDialog(null, "Name Can't Be Empty", "Error", 1);
        } else if (pin2.getText().length() < 3) {
            JOptionPane.showMessageDialog(null, "pin Can't Be Less than 4 Digit", "Error", 1);
        } else if (phoneno3.getText().length() != 10) {
            JOptionPane.showMessageDialog(null, "Please Enter a Valid Phone No", "Error", 1);
        } else {
            Connection conn = null;
            PreparedStatement pstmt = null;
            ResultSet rs = null;
            String name = nn.getText();
            String phone = phoneno3.getText();
            String dir = "D:\\" + name + phone;

            try {
                File theDir = new File(dir);

                // if the directory does not exist, create it
                if (!theDir.exists()) {
                    System.out.println("creating directory: " + theDir.getName());
                    boolean result = false;
                    theDir.mkdir();
                    result = true;
                    if (result) {
                        System.out.println("DIR created");
                        conn = DriverManager.getConnection("jdbc:mysql://localhost/locker", "root", "123456");
                        String sql = " insert into login (name, pin, phoneno,dir) values (?,?,?,?)";
                        PreparedStatement pst = conn.prepareStatement(sql);

                        pst.setString(1, nn.getText());
                        pst.setString(2, pin2.getText());
                        pst.setString(3, phoneno3.getText());
                        pst.setString(4, dir);

                        pst.execute();
                        pst.close();
                        JOptionPane.showMessageDialog(null, "Register Succesfully.....");

                    }
                } else {
                    JOptionPane.showMessageDialog(null, " Can Not Register,\n Try Somthing new Name.......");
                }

            } catch (Exception ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(null, "error");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Addauser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Addauser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Addauser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Addauser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Addauser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField nn;
    private javax.swing.JTextField phoneno3;
    private javax.swing.JTextField pin2;
    // End of variables declaration//GEN-END:variables
}
