/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package file_locker.pkg3_level_sequrity;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Random;
import javax.swing.JOptionPane;

public class First extends javax.swing.JFrame {

    String Phoneno;
    String dir;

    private final String USER_AGENT = "Mozilla/5.0";

    public First() {
        initComponents();
        setBounds(new java.awt.Rectangle(1, 1, 750, 470));
        setResizable(false);
        setTitle("File Locker");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setFont(new java.awt.Font("Tempus Sans ITC", 3, 36)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/file_locker/pkg3_level_sequrity/images/add-friend.png"))); // NOI18N
        jButton1.setText("Add a user");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(260, 240, 390, 157);

        jButton2.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/file_locker/pkg3_level_sequrity/images/settings-work-tool.png"))); // NOI18N
        jButton2.setText("Setting");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(570, 30, 140, 41);

        jButton4.setFont(new java.awt.Font("Tempus Sans ITC", 3, 36)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/file_locker/pkg3_level_sequrity/images/top-secret.png"))); // NOI18N
        jButton4.setText("Go To Locker");
        jButton4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jButton4.setBorderPainted(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(90, 40, 360, 157);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/file_locker/pkg3_level_sequrity/images/Capture.JPG"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -90, 740, 550);
        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        Addauser au = new Addauser();
        au.setVisible(true);
        //database store


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String pin1 = JOptionPane.showInputDialog(null, "Enter Your Pin/Password", "File locker", 1);
        System.out.println(pin1);
        //database.......
        Connection con = null;
        ResultSet rs = null;
        Statement stmt = null;
        String sql = "select phoneno,name,dir from login where pin = \"" + pin1 + "\"";
        try {

            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/locker", "root", "123456");
            stmt = con.createStatement();
            rs = stmt.executeQuery(sql);

            if (rs.next()) {
                Phoneno = rs.getString("phoneno");
                String name = rs.getString("name");
                dir = rs.getString("dir");

                JOptionPane.showConfirmDialog(null, "Wellcome " + name + "\nlogin successfully");

                //generate otp
                Random ran = new Random();

                int a = ran.nextInt();
                a = a % 100000;
                while (a < 0) {
                    a = a * (-1);
                }
                String OTPs = Integer.toString(a);

                //sending OTP section................................................
                //System.out.print(OTPs);
                //send otp
                String url = "https://www.fast2sms.com/dev/bulk?authorization=PmcQKOHzt9qCT2pniBayAVFroUxWkRfLSdI0YMX6ulDs81g4ZNJPb91GH0LWR4UhEt6ywKIgurQTsmA3&sender_id=FSTSMS&language=english&route=qt&numbers=" + Phoneno + "&message=8341&variables={AA}&variables_values=" + OTPs;

                URL obj = new URL(url);
                HttpURLConnection conn = (HttpURLConnection) obj.openConnection();

                conn.setRequestMethod("GET");

                conn.setRequestProperty("User-Agent", USER_AGENT);
                int responseCode = conn.getResponseCode();

                System.out.println("\nSending 'GET' request to URL : " + url);
                System.out.println("Response Code : " + responseCode);

                BufferedReader in = new BufferedReader(
                        new InputStreamReader(conn.getInputStream()));
                String inputLine;
                StringBuffer response = new StringBuffer();

                while ((inputLine = in.readLine()) != null) {
                    response.append(inputLine);
                }
                in.close();

                //print result
                System.out.println(response.toString());

                //check otp
                String OTPr = JOptionPane.showInputDialog("Enter the OTP", DISPOSE_ON_CLOSE);
                if (OTPs.equals(OTPr)) {

                    new Master_User(dir).setVisible(true);
                    stmt.close();
                }

            } else {
                JOptionPane.showMessageDialog(null, "no Such User");
                System.exit(1);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            e.printStackTrace();
        }


    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Setting s = new Setting();
        s.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(First.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(First.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(First.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(First.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new First().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
