/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package file_locker.pkg3_level_sequrity;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Random;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;

/**
 *
 * @author HP
 */
public class Setting extends javax.swing.JFrame {

    private final String USER_AGENT = "Mozilla/5.0";
    /**
     * Creates new form Setting
     */
    public Setting() {
        initComponents();
        setBounds(new java.awt.Rectangle(1, 1, 685, 545));
        setResizable(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/file_locker/pkg3_level_sequrity/images/padlock (1).png"))); // NOI18N
        jButton1.setText("    Change Pin");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(160, 140, 340, 70);

        jButton2.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Downloads\\smartphone.png")); // NOI18N
        jButton2.setText("  Update Phone No");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(160, 290, 340, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/file_locker/pkg3_level_sequrity/images/Capture.JPG"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 680, 515);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String name = JOptionPane.showInputDialog(null, "enter the name", DISPOSE_ON_CLOSE);
        String phoneno = JOptionPane.showInputDialog(null, "enter the phone no", DISPOSE_ON_CLOSE);
        //check details
        Connection con = null;
        ResultSet rs = null;
        ResultSet rs1 = null;
        Statement stmt = null;
        Statement stmt1 = null;
        String sql = "select phoneno,name from login where phoneno = \"" + phoneno + "\"";
        try {

            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/locker", "root", "123456");
            //JOptionPane.showMessageDialog(null, "1");
            stmt = con.createStatement();

            rs = stmt.executeQuery(sql);
            if (rs.next()) {
                String name1 = rs.getString("name");
                if (name1.equals(name)) {
                    //generate otp
                    Random ran = new Random();
                    int a = ran.nextInt();
                    a = a % 100000;
                    while (a < 0) {
                        a = a * (-1);
                    }
                    String OTPs = Integer.toString(a);
                    //***************************************************
                    String url = "https://www.fast2sms.com/dev/bulk?authorization=PmcQKOHzt9qCT2pniBayAVFroUxWkRfLSdI0YMX6ulDs81g4ZNJPb91GH0LWR4UhEt6ywKIgurQTsmA3&sender_id=FSTSMS&language=english&route=qt&numbers=" + phoneno + "&message=8341&variables={AA}&variables_values=" + OTPs;
                    URL obj = new URL(url);
                    HttpURLConnection conn = (HttpURLConnection) obj.openConnection();
                    conn.setRequestMethod("GET");
                    conn.setRequestProperty("User-Agent", USER_AGENT);
                    int responseCode = conn.getResponseCode();
                    System.out.println("\nSending 'GET' request to URL : " + url);
                    System.out.println("Response Code : " + responseCode);
                    BufferedReader in = new BufferedReader(
                            new InputStreamReader(conn.getInputStream()));
                    String inputLine;
                    StringBuffer response = new StringBuffer();
                    while ((inputLine = in.readLine()) != null) {
                        response.append(inputLine);
                    }
                    in.close();
                    rs.close();
                    stmt.close();
                    System.out.println(response.toString());
                    //check otp
                    String OTPr = JOptionPane.showInputDialog("Enter the OTP", DISPOSE_ON_CLOSE);
                    if (OTPs.equals(OTPr)) {
                        //update pin;
                        String newpin = JOptionPane.showInputDialog("Enter the new pin", DISPOSE_ON_CLOSE);
                        String sql2 = "update login set pin=\"" + newpin + "\" where phoneno=\"" + phoneno + "\"";
                        try {
                            Class.forName("com.mysql.jdbc.Driver");
                            stmt1 = con.createStatement();
                            JOptionPane.showConfirmDialog(null, "1");
                            stmt1.executeUpdate(sql2);
                            JOptionPane.showConfirmDialog(null, "done");
                            stmt.close();
                        } catch (Exception ex) {
                            System.out.println(ex);
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "You Have Entered Wrong OTP");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "You Have Entered Wrong Detail");
                }
            } else {
                JOptionPane.showMessageDialog(null, "no Such User");
                System.exit(1);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            e.printStackTrace();
        }

        //send otp;
        //verify otp;

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String name = JOptionPane.showInputDialog(null, "enter the name", DISPOSE_ON_CLOSE); // TODO add your handling code here:
        String pin = JOptionPane.showInputDialog(null, "enter the pin", DISPOSE_ON_CLOSE);
        String phoneno = JOptionPane.showInputDialog(null, "enter the previous Phone No", DISPOSE_ON_CLOSE);
        //update phoneno
        Connection con = null;
        ResultSet rs = null;
        Statement stmt = null;
        String pinD = "";
        String nameD = "";

        String sql = "select pin, name from login where phoneno = \"" + phoneno + "\"";
        try {

            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/locker", "root", "123456");
            JOptionPane.showMessageDialog(null, "1");
            stmt = con.createStatement();
            JOptionPane.showMessageDialog(null, "2");
            rs = stmt.executeQuery(sql);
            JOptionPane.showMessageDialog(null, "3");
            if (rs.next()) {
                JOptionPane.showMessageDialog(null, "4");
                pinD = rs.getString("pin");
                nameD = rs.getString("name");
            } else {
                JOptionPane.showConfirmDialog(null, "No Such User...");
            }

            JOptionPane.showMessageDialog(null, "5");
            if (nameD.equals(name) && pinD.equals(pin)) {
                JOptionPane.showMessageDialog(null, "6");
                String newphoneno = JOptionPane.showInputDialog(null, "enter the new Phone No", DISPOSE_ON_CLOSE);
                if (newphoneno.length() == 10) {
                    ResultSet rs1 = null;
                    Statement stmt1 = null;
                    String sql1 = "update login set phoneno=\"" + newphoneno + "\" where phoneno=\"" + phoneno + "\"";
                    stmt.executeUpdate(sql1);
                    if (rs.next()) {
                        JOptionPane.showConfirmDialog(null, "Succesfully Updated");
                    } else {
                        JOptionPane.showConfirmDialog(null, "Somthing Went Wrong");
                    }

                } else {
                    JOptionPane.showConfirmDialog(null, "Please Enter the Valid Phone no ");
                }

            } else {
                JOptionPane.showConfirmDialog(null, "Entered Details are Wrong......");
            }

        } catch (Exception ex) {
            System.out.println(ex);
        }


    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Setting().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
